name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - run: npm install -g surge
      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain zonked-scale.surge.sh
        env: 
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
