name: CI
on:
  push:
  pull_request:
    branches: [develop]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use Nodejs
        uses: action/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run test -- --coverage
        env:
          CI: true
